#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

cd "$(dirname "$0")"
echo "Running tests..."
pytest "$@"
# Can assume success because of set -e
echo "All tests passed successfully!"
